### ISSUE TITLE
setGyroscopePeriod returning a missing UUID error

### ISSUE THREAD

**Issue by tigoe** [sandeepmistry/node-sensortag#104]
When I call setGyroscopePeriod(), I consistently get this non-fatal error:  

 Error: characteristic uuid f000aa5304514000b000000000000000 not found in service uuid f000aa5004514000b000000000000000!

Checking with lightBlue, sure enough, my 2541 tags do not have that characteristic in their gyro service. 

FWIW, my vital stats:
 firmware revision = 1.4 (Jul 12 2013)
 system id = bc:6a:29:00:00:ab:4e:82

I can't find the link to the 2541 data sheet that has the full list of UUIDs, but if/when I find it I'll post more info if I find any.

**Comment by tigoe** [comment]
Problem solved. 2541 needs firmware version later than 1.4 for gyroscope period. Thanks to http://processors.wiki.ti.com/index.php/SensorTag_User_Guide

**Comment by sandeepmistry** [comment]
Added note in read me about the firmware version https://github.com/sandeepmistry/node-sensortag/commit/3fb66095266e44f8e2a73254fb5fe5654aa72747.
