### ISSUE TITLE
No connection with Noble version 1.9

### ISSUE THREAD

**Issue by martin-doyle** [sandeepmistry/node-sensortag#107]
After reinstalling node-sensortag, I could not connect to the TI-Sensortag anymore. The script hangs at the connectAndSetup function. Since node-sensortag (1.3) and noble-device (1.41) have not changed, the change on noble to 1.9 seems to be the problem. After forcing version 1.81, everything works fine again.

**Comment by jmjobin** [comment]
Had the same problem and resolved it by forcing install noble@1.8. Thanks for the hint.

**Comment by curana** [comment]
I can confirm that
a) on my Macbook (High Sierra) it works with noble 1.9
b) on my Raspberry Pi 3 (current Raspbian) it does not work with noble 1.9. Downgrading to noble 1.8.1 fixes the connection issues.

With the RPi3 noble/sensortag hangs after connecting to the CC2650. It won't succeed in activating the sensors.

**Comment by kevintupper** [comment]
Confirm as well!  After hours of trying to figure out why a demo wasn't working.  :-)

**Comment by sandeepmistry** [comment]
This should be fixed with https://github.com/noble/noble/pull/769. Please provide your feedback on that pull request.

**Comment by piersbarrios** [comment]
Thank you very much! I have been strugling for three days before finding this was the issue. 

Works perfectly on RaspberryPi 3 (tell me if you want more details)

**Comment by martin-doyle** [comment]
Yes, it works with version 1.9 and https://github.com/noble/noble/pull/769 on a Raspberry.
Thanks a lot.

**Comment by sandeepmistry** [comment]
noble v1.9.1 has been published with a fix for this.
