### ISSUE TITLE
Sensing multiple passing tags

### ISSUE THREAD

**Issue by paultanner** [sandeepmistry/node-sensortag#26]
If you call discover and find a tag you get the callback and all goes well.
However, if another tag then approaches this will be invisible
(testing on Rpi with raspbian and node 10.7)

So I am wondering how one might be able to do further discoveries. I tried:
```
var sensorTag = require('sensortag');

setInterval(function() {
  console.log('waiting ...');
  sensorTag.discover(function(sensorTag) {

    sensorTag.on('disconnect', function() {
      console.log('disconnected');
    });

    sensorTag.connect(function() {
      // a quick way to get the tag's mac address
      console.log(sensorTag.uuid + " connected");
    });
  });
},2000);
```
.. which is not only inelegant but crashes before long

Is there a good way to do this?
Thx. Paul

**Comment by sandeepmistry** [comment]
@paultanner are you still interested in this?

If so, using [noble-device](https://github.com/sandeepmistry/noble-device) instead of noble directly for the library is the way to go.

**Comment by sandeepmistry** [comment]
@paultanner there is a ```SensorTag.discoverAll``` API in master now.
