### ISSUE TITLE
discoverServicesAndCharacteristics(callback) hangs

### ISSUE THREAD

**Issue by leucir** [sandeepmistry/node-sensortag#30]
After connecting, I try to discover services but it hangs.
I'm using Yosemite.
Any tips?

**Comment by sandeepmistry** [comment]
@leucir which version of noble / node-sensortag are you using? (run ```npm ls```)

Can you share the node.js app you are using? Also, output of debug: ```DEBUG=bindings node <file>.js```

**Comment by leucir** [comment]
@sandeepmistry , thanks for your reply.
I could make it work.
Thanks anyway.
