### ISSUE TITLE
Custom BluetoothApp on CC2650DK

### ISSUE THREAD

**Issue by arunn-tp** [sandeepmistry/node-sensortag#38]
Hi Guys.

Im relatively new to TI platform and got an opportunity to develop a custom Bluetooth application using CC2650DK

I have got my hands on two CC2650 Development Kit which involves two CC2650 Evaluation Modules, two SmartRF06 Boards.

We are using the default Bluetooth-stack2 on Code composer studio IDE 
My requirement is to get the Rssi of both the bluetooth module on LCD without using the existing menu based application which is preloaded 
Please help me to get around and understand the code and do the necessary modifications to complete my requirements

**Comment by sandeepmistry** [comment]
@arunn-tp as mentioned before this is not the right place to ask your question, as it seems unrelated to node-sensortag and noble.
