### ISSUE TITLE
npm install sensortag install on RaspBerry PI problems

### ISSUE THREAD

**Issue by urhlednik** [sandeepmistry/node-sensortag#6]
Hello guys,

Can anybody give me a hint how to fix following error?

Thanks for help.

---

 sudo npm install sensortag
npm http GET https://registry.npmjs.org/sensortag
npm http 304 https://registry.npmjs.org/sensortag
npm http GET https://registry.npmjs.org/noble
npm http 304 https://registry.npmjs.org/noble
npm http GET https://registry.npmjs.org/debug
npm http 304 https://registry.npmjs.org/debug

> noble@0.2.4 install /home/pi/node_modules/sensortag/node_modules/noble
> node install.js

noble install: platform is "linux'
noble install: running node-gyp ...
gyp ERR! configure error
gyp ERR! stack Error: "pre" versions of node cannot be installed, use the --nodedir flag instead
gyp ERR! stack     at install (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/install.js:65:16)
gyp ERR! stack     at Object.self.commands.(anonymous function) [as install](/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/node-gyp.js:66:37)
gyp ERR! stack     at getNodeDir (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/configure.js:150:20)
gyp ERR! stack     at /usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/configure.js:93:9
gyp ERR! stack     at ChildProcess.exithandler (child_process.js:659:7)
gyp ERR! stack     at ChildProcess.EventEmitter.emit (events.js:101:17)
gyp ERR! stack     at maybeClose (child_process.js:773:16)
gyp ERR! stack     at Socket.<anonymous> (child_process.js:993:11)
gyp ERR! stack     at Socket.EventEmitter.emit (events.js:98:17)
gyp ERR! stack     at Pipe.close (net.js:459:12)
gyp ERR! System Linux 3.6.11+
gyp ERR! command "node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "configure" "build"
gyp ERR! cwd /home/pi/node_modules/sensortag/node_modules/noble
gyp ERR! node -v v0.11.10-pre
gyp ERR! node-gyp -v v0.12.1
gyp ERR! not ok
noble install: done
npm ERR! noble@0.2.4 install: `node install.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the noble@0.2.4 install script.
npm ERR! This is most likely a problem with the noble package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node install.js
npm ERR! You can get their info via:
npm ERR!     npm owner ls noble
npm ERR! There is likely additional logging output above.

npm ERR! System Linux 3.6.11+
npm ERR! command "/usr/local/bin/node" "/usr/local/bin/npm" "install" "sensortag"
npm ERR! cwd /home/pi
npm ERR! node -v v0.11.10-pre
npm ERR! npm -v 1.3.15
npm ERR! code ELIFECYCLE
npm ERR!
npm ERR! Additional logging details can be found in:
npm ERR!     /home/pi/npm-debug.log
npm ERR! not ok code 0

**Comment by rjsteinert** [comment]
I just got this working on a Raspberry Pi 2 using the [Pirateship for Pi build](http://openpipekit.github.io/pirate.sh/#!index.md). I followed the instructions [here](http://www.elinux.org/RPi_Bluetooth_LE) for getting the BLE stuff enabled and I'm using the suggested "Plugable USB-BT4LE adapter".  Pirateship for Pi is running node v0.12.6.
