### ISSUE TITLE
is OAD support something you would like to add?

### ISSUE THREAD

**Issue by epoger** [sandeepmistry/node-sensortag#75]
Hey Sandeep-

Thanks for creating this great library!

Is OAD (Over-the-Air Download of new firmware to the CC2650 SensorTag) something you would like to be part of the library?  Or is there some reason you wouldn't want it to be?

No, I haven't written the code yet, just wondering if it's something I should do. :-)

**Comment by sandeepmistry** [comment]
@epoger I'd be open to merging a PR for it.

What use case do you have in mind? Is it possible to get an official firmware binary from TI outside the mobile app?

**Comment by sandeepmistry** [comment]
I'm closing this for now, due to lack of discussion.
