### ISSUE TITLE
Read all sensors at once

### ISSUE THREAD

**Issue by meeximum** [sandeepmistry/node-sensortag#76]
Hi,

what would be the best approach to read all values at once?
I tried with async.parallel() but it doesn't worked :-/

regards
Meex

**Comment by sandeepmistry** [comment]
@meeximum could you please share what you've tried so far?

Maybe something like [test.js](https://github.com/sandeepmistry/node-sensortag/blob/master/test.js) but to enable notifications on each sensor instead and listen for events.

**Comment by meeximum** [comment]
@sandeepmistry ok when I do like in test.js, I just need to comment out the setTimeout(function() {} to make it run forever?

**Comment by sandeepmistry** [comment]
@meeximum see something like this: https://github.com/tigoe/BluetoothLE-Examples/blob/master/sensorTag/sensorTagExample/sensortagIRTemperature.js
