### ISSUE TITLE
Stop SensorTag.discoverById?

### ISSUE THREAD

**Issue by stozk** [sandeepmistry/node-sensortag#78]
Hi,
is it possible to stop SensorTag.discoverById looking for a Tag or do I have to use my own implementation of discoverAll() respectively stopDiscoverAll() and add a timeout there?

This is how I do it currently:

```
function checkConnect(){
 if(!sensorConnected){
            console.log('Sensor connection timeout!');
            SensorTag.stopDiscoverAll(onDiscover);
            startScan();
        }
    }
    setTimeout(checkConnect, 10000);
    SensorTag.discoverAll(onDiscover);
    function onDiscover(sensorTag) {
        if(sensorTag.id === deviceId){...
```

Thanks & BR
Daniel

**Comment by sandeepmistry** [comment]
@stozk there are no `stopDiscoverById` API's at this time, you can follow this for further related info on this topic: https://github.com/sandeepmistry/noble-device/issues/10

> do I have to use my own implementation of discoverAll() respectively stopDiscoverAll() and add a timeout there?

Yes, this is what I would recommend for now.
