### ISSUE TITLE
Trying to read all sensors test.js but keep getting a memory leak

### ISSUE THREAD

**Issue by OtisHarrison24** [sandeepmistry/node-sensortag#85]
Hi I have been trying to read all sensor like the test.js but more like the example where you can hit the two side buttons to disconnect but keep getting a memory like / things go crazy. thanks

**Comment by sandeepmistry** [comment]
@OtisHarrison24 please provide more details, code example etc.

**Comment by sandeepmistry** [comment]
Probably related to https://github.com/sandeepmistry/node-sensortag/issues/83, closing for now.
