### ISSUE TITLE
Detecting sensortag continuously 

### ISSUE THREAD

**Issue by arunseba** [sandeepmistry/node-sensortag#88]
how to detect sensor tag continuously until we stop detecting manually. i want to take temperature in room with multiple sensor tag simultaneously..

**Comment by sandeepmistry** [comment]
Hi @arunseba,

I've added a short example here: https://github.com/sandeepmistry/node-sensortag/blob/master/test-continous-discover-connect.js

You will have to fill in the temperature stuff, it just shows continuous discovery and connecting.
