### ISSUE TITLE
Check battery level on CC2650

### ISSUE THREAD

**Issue by craigmw** [sandeepmistry/node-sensortag#90]
TI has recently provided a method to read the battery level on the SensorTag. Is there any way to read this value using your node-sensortag library?

**Comment by sandeepmistry** [comment]
@craigmw please see pull request #82.

It's not ready to merge yet, but if you can try out my suggestion in https://github.com/sandeepmistry/node-sensortag/pull/82#issuecomment-241288978 and submit a new pull request if it works, that would be great.

**Comment by craigmw** [comment]
Thanks Sandeep. I'll try this out and report back.

**Comment by sandeepmistry** [comment]
@craigmw have you made any progress on this?

**Comment by sandeepmistry** [comment]
@craigmw ping ...

**Comment by danielbh** [comment]
It looks like this is available with 1.3 revision! Check out the dev app!

![img_5069](https://cloud.githubusercontent.com/assets/6653234/21547541/0930ebba-cde7-11e6-9ac8-a8d7115175f9.PNG)

**Comment by sandeepmistry** [comment]
Fixed via #93.
