### ISSUE TITLE
How to get the battery level?

### ISSUE THREAD

**Issue by rei-vilo** [sandeepmistry/node-sensortag#94]
[added battery service mixin from noble](https://github.com/sandeepmistry/node-sensortag/commit/3e9a664db167413e599b9f679e1ac84b5a29e423) has just been added, but how to get the battery level?

Thank you!

**Comment by micahnyc** [comment]
Hi @rei-vilo you can read the battery in a similar way to the other properties:

tag.readBatteryLevel(function(error, batteryLevel) {
     console.log(tag.id, " battery read with error:", error, " level:", batteryLevel);
});

**Comment by sandeepmistry** [comment]
@micahnyc thank's for helping out!

I've added it to the read me in https://github.com/sandeepmistry/node-sensortag/commit/27d820558c535a06aa8a78fd6607a026b2579292.

**Comment by abataille** [comment]
I tried this, but get:
 tag.readBatteryLevel(function(error, batteryLevel) {
            ^
TypeError: tag.readBatteryLevel is not a function
I cannot find it in version 1.2.3.

**Comment by sandeepmistry** [comment]
v1.3.0 has been published to npm with the new feature.
