### ISSUE TITLE
read battery level

### ISSUE THREAD

**Issue by abataille** [sandeepmistry/node-sensortag#95]
I tried this, but get:
tag.readBatteryLevel(function(error, batteryLevel) {
^
TypeError: tag.readBatteryLevel is not a function
I cannot find it in version 1.2.3. 
If you have, it would be nice to a new version.

**Comment by micahnyc** [comment]
@abataille since this feature was added w/o a updated version number, perhaps you just don't have the updated code in your project. Try deleting the node-sensortag folder from your node_modules/ folder and then run npm install again.

@sandeepmistry perhaps a 1.2.4 version is a good idea.

**Comment by sandeepmistry** [comment]
@abataille @micahnyc I've just published v1.3.0 to npm with the new feature.

@micahnyc thanks for the reminder!
