### ISSUE TITLE
 Connection Control Service

### ISSUE THREAD

**Issue by nitishagarwal1225** [sandeepmistry/node-sensortag#97]
Hello,
I am new to BLE. Currently, I am doing an internship where I am using RPI with node-red to communicate with TI sensor Tag. I was asked by my supervisor to set Connection parameters. How Can I do so?

**Comment by sandeepmistry** [comment]
@nitishagarwal1225 this is currently not supported in the module or by the lower level noble module it builds on.

Pull requests welcome.
