### ISSUE TITLE
Unable to update to V1.3 to read Battery Level 

### ISSUE THREAD

**Issue by Clause16** [sandeepmistry/node-sensortag#99]
This issue is a follow up on #98, since the issue has been closed but yet to be resolved. Thanks in advance for your help!

**Comment by sandeepmistry** [comment]
@Clause16 please see my comments in https://github.com/sandeepmistry/node-sensortag/issues/98#issuecomment-285990394 and https://github.com/sandeepmistry/node-sensortag/issues/98#issuecomment-286068631

If those are not helpful, please contact the `node-red-node-sensortag` maintainers here: https://github.com/node-red/node-red-nodes/issues
